#
# BEWARE OF EDITING ~/.bashrc BY HAND!
#
# ~/.bashrc is generated by putes:linux/setup.sh
# To change it, edit the source files and run setup.sh
#
# below here should have been taken directly from /etc/skel/.bashrc
#
