#
# above here should have been taken directly from /etc/skel/.bashrc
#
# BEWARE OF EDITING ~/.bashrc BY HAND!
#
# ~/.bashrc is generated by putes:linux/setup.sh
# To change it, edit the source files and run setup.sh
#

if [[ "${-}" == *i* ]]; then
    echo -e "$(date)\t####-->> Starting  Thad's additions to .bashrc <<--####" | tee -a "${HOME}/log/tevent.log" | cut -f2-
    for _putes_f in "${HOME}/etc/bash/rc/"*.bash; do
        [[ -r "${_putes_f}" ]] && source "${_putes_f}"
    done
    unset _putes_f
    echo -e "$(date)\t####-->> Done with Thad's additions to .bashrc <<--####" | tee -a "${HOME}/log/tevent.log" | cut -f2-
fi
