# ~/.bashrc — generated by putes linux/setup.sh; do not edit this file by hand.
# Change linux/base/bashrc.dotfile.*.bash and linux/*/home/etc/bash/rc/*.bash, then re-run:
#   ./linux/setup.sh workstation   or   ./linux/setup.sh server
#
