export VM_MSWIN=win11

# for util:
export TOKMINT_SECCONFIG_SUBDIR=tokmint
export TOKMINT_PORT=9876
export TOKMINT_LOG_LEVEL=INFO
export TOKMINT_UNSAFE_LOGGING=unset
export TOKMINT_JSONL_FMT_FLUSH_MS=1000
